name: bmi_calculator
description: Practicing Flutter.
version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.15.0
  division: ^0.8.7+2
  share:
  async_redux: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/